services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logger: '@?monolog.logger.stripe'

    Softspring\PlatformBundle\Stripe\Transformer\ProductTransformer: ~

    Softspring\PlatformBundle\Stripe\EntityListener\ProductEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_subscription.product.class%' } # , entity_manager: '%sfs_subscription.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_subscription.product.class%' } # , entity_manager: '%sfs_subscription.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_subscription.product.class%' } # , entity_manager: '%sfs_subscription.entity_manager_name%' }

    Softspring\PlatformBundle\Stripe\Adapter\ProductAdapter:
        tags:
            - { name: 'sfs_platform.adapter', model: 'product', platform: 'stripe' }