services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logger: '@?monolog.logger.stripe'

    Softspring\PlatformBundle\Stripe\Transformer\PlanTransformer: ~

    Softspring\PlatformBundle\Stripe\EntityListener\PlanEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_subscription.plan.class%' } # , entity_manager: '%sfs_subscription.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_subscription.plan.class%' } # , entity_manager: '%sfs_subscription.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_subscription.plan.class%' } # , entity_manager: '%sfs_subscription.entity_manager_name%' }

    Softspring\PlatformBundle\Stripe\Adapter\PlanAdapter:
        tags:
            - { name: 'sfs_platform.adapter', model: 'plan', platform: 'stripe' }