services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\PlatformBundle\Stripe\Transformer\SourceTransformer: ~

    Softspring\PlatformBundle\Stripe\Adapter\SourceAdapter:
        tags:
          - { name: 'sfs_platform.adapter', model: 'source', platform: 'stripe' }

    Softspring\PlatformBundle\Stripe\EntityListener\SourceEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_customer.source.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_customer.source.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_customer.source.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
