services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logger: '@?monolog.logger.stripe'

    Softspring\PlatformBundle\Stripe\Transformer\CustomerTransformer: ~

    Softspring\PlatformBundle\Stripe\Adapter\CustomerAdapter:
        tags:
            - { name: 'sfs_platform.adapter', model: 'customer', platform: 'stripe' }

    Softspring\PlatformBundle\Stripe\Adapter\AddressAdapter:
        tags:
          - { name: 'sfs_platform.adapter', model: 'address', platform: 'stripe' }

    Softspring\PlatformBundle\Stripe\EntityListener\AddressEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_customer.address.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_customer.address.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_customer.address.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }

    Softspring\PlatformBundle\Stripe\EntityListener\CustomerEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_customer.customer.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_customer.customer.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_customer.customer.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }

