#services:
#    _defaults:
#        autowire: true
#        autoconfigure: true
#        public: false
#
#    Softspring\PlatformBundle\Stripe\Event\WebhookEventFactory:
#        tags: ['sfs_platform.webhook_event_factory']
