services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\PlatformBundle\Manager\AdapterManagerInterface:
        class: Softspring\PlatformBundle\Manager\AdapterManager
        arguments:
            $adapters: []