services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\PlatformBundle\Twig\Extension\:
        resource: '../../../Twig/Extension'
        tags: ['twig.extension']